### ISSUE TITLE
Issue for running `gulp`

### ISSUE THREAD

**Issue by 0x333333** [michaelbromley/angular-es6#8]
Hi,

I came across this issue when I did `gulp` after `npm i`.

``` shell
/Users/zhipeng/Development/angular-es6/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^

TypeError: less.render(...).then(...).catch(...).done is not a function
    at DestroyableTransform._transform (/Users/zhipeng/Development/angular-es6/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/Users/zhipeng/Development/angular-es6/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/zhipeng/Development/angular-es6/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/zhipeng/Development/angular-es6/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/zhipeng/Development/angular-es6/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/zhipeng/Development/angular-es6/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/zhipeng/Development/angular-es6/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/zhipeng/Development/angular-es6/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/zhipeng/Development/angular-es6/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
```

I searched a little bit, then I found this [https://github.com/plus3network/gulp-less/issues/140](https://github.com/plus3network/gulp-less/issues/140), in the previous version of gulp-less there was not such a function `done()`. That issue can be fixed simply by using the latest version of gulp-less. I try that and it works.

So I will request a PR to bump the version of gulp-less, can you have a look at this? 

Thanks in advance!

**Comment by michaelbromley** [comment]
Thanks - merged!
